import React, { useState, useEffect } from 'react';
import { BrowserRouter as Router, Routes, Route, Navigate, Link } from 'react-router-dom';
import Dashboard from './pages/hr/Dashboard';
import CreateInterview from './pages/hr/CreateInterview';
import ReportView from './pages/hr/ReportView';
import InterviewPortal from './pages/candidate/InterviewPortal';
import ThankYouScreen from './pages/candidate/ThankYouScreen';
import { motion } from 'motion/react';
import { Users, FileText, Zap } from 'lucide-react';

export default function App() {
  const [hasApiKey, setHasApiKey] = useState<boolean | null>(null);

  useEffect(() => {
    const checkKey = async () => {
      if ((window as any).aistudio && (window as any).aistudio.hasSelectedApiKey) {
        const hasKey = await (window as any).aistudio.hasSelectedApiKey();
        setHasApiKey(hasKey);
      } else {
        setHasApiKey(true);
      }
    };
    checkKey();
  }, []);

  const handleSelectKey = async () => {
    if ((window as any).aistudio && (window as any).aistudio.openSelectKey) {
      await (window as any).aistudio.openSelectKey();
      setHasApiKey(true);
    }
  };

  if (hasApiKey === false) {
    return (
      <div className="min-h-screen bg-gray-50 font-sans text-gray-900 flex flex-col items-center justify-center p-6 text-center">
        <h2 className="text-3xl font-bold text-gray-900 mb-4">API Key Required</h2>
        <p className="text-gray-600 max-w-md mb-8">
          To use the advanced Pro models without strict quota limits, please select your Google Cloud API Key.
          <br/><br/>
          <a href="https://ai.google.dev/gemini-api/docs/billing" target="_blank" rel="noreferrer" className="text-indigo-600 hover:underline">
            Learn about billing and API keys
          </a>
        </p>
        <button 
          onClick={handleSelectKey}
          className="px-6 py-3 bg-indigo-600 text-white rounded-xl font-medium hover:bg-indigo-700 transition-colors"
        >
          Select API Key
        </button>
      </div>
    );
  }

  // A simple splash page since we no longer have a monolithic starting point
  const LandingPage = () => (
    <div className="min-h-screen bg-gray-50 flex flex-col items-center justify-center p-6 bg-gradient-to-br from-indigo-50 to-emerald-50 text-center">
      <motion.div initial={{ opacity: 0, scale: 0.95 }} animate={{ opacity: 1, scale: 1 }} className="max-w-2xl">
        <div className="w-20 h-20 bg-indigo-600 text-white rounded-2xl flex items-center justify-center mx-auto mb-8 shadow-xl shadow-indigo-200">
          <Zap size={40} />
        </div>
        <h1 className="text-5xl font-extrabold tracking-tight text-gray-900 mb-6">
          AI Tech Interviewer
        </h1>
        <p className="text-xl text-gray-600 mb-12">
          An autonomous technical interviewing platform. Select your portal to begin.
        </p>
        
        <div className="grid md:grid-cols-2 gap-6">
          <Link to="/hr" className="bg-white p-8 rounded-3xl shadow-sm border border-gray-100 hover:border-indigo-200 hover:shadow-md transition-all group">
            <div className="w-14 h-14 bg-indigo-50 text-indigo-600 rounded-xl flex items-center justify-center mx-auto mb-6 group-hover:scale-110 transition-transform">
              <Users size={28} />
            </div>
            <h2 className="text-2xl font-bold text-gray-900 mb-3">HR Panel</h2>
            <p className="text-gray-500 text-sm">Create interviews, manage candidates, and view AI-generated reports.</p>
          </Link>

          <div className="bg-white/50 p-8 rounded-3xl border border-gray-100/50 flex flex-col items-center justify-center">
            <div className="w-14 h-14 bg-gray-100 text-gray-400 rounded-xl flex items-center justify-center mx-auto mb-6">
              <FileText size={28} />
            </div>
            <h2 className="text-2xl font-bold text-gray-400 mb-3">Candidate Entry</h2>
            <p className="text-gray-400 text-sm">Candidates must use their unique /invite link generated by HR.</p>
          </div>
        </div>
      </motion.div>
    </div>
  );

  return (
    <Router>
      <Routes>
        {/* Core Entry */}
        <Route path="/" element={<LandingPage />} />
        
        {/* HR Portal */}
        <Route path="/hr" element={<Dashboard />} />
        <Route path="/hr/new" element={<CreateInterview />} />
        <Route path="/hr/report/:id" element={<ReportView />} />
        
        {/* Candidate Portal */}
        <Route path="/invite/:id" element={<InterviewPortal />} />
        <Route path="/thank-you" element={<ThankYouScreen />} />
        
        {/* Fallback */}
        <Route path="*" element={<Navigate to="/" replace />} />
      </Routes>
    </Router>
  );
}
